### ISSUE TITLE
File Extension Error

### ISSUE THREAD

**Issue by kaldenficklin** [zab/zab-cli#16]
variable for a zip code 'ng-model="vm.course.zip"' got preprended with a cdn url throwing angular sytanx error

`Error: [$parse:syntax]`

Changed to 'ng-model="vm.course.zipcode"' to fix the issue

**Comment by tannerlinsley** [comment]
Interesting. Most likely because of the zip suffix

**Comment by jdmaurer** [comment]
Yeah, it thinks it's a zip file...

**Comment by jdmaurer** [comment]
I wonder what the best way to approach this would be... Check the nature of the enclosing tag and emit any that have ng (or other directives from different frameworks)? Provide a way for the user to manually escape it from the cdnex? This is kind of a weird use case, I wonder how common it is to do something like this.

**Comment by jsonmaur** [comment]
This also happened on the new HQ site with writing an email in quotes in a paragraph of text, for reference.
`We didn’t want a "matt@reallycoolbutlongname.com" email.`

**Comment by jsonmaur** [comment]
Closed with new code at https://github.com/jsonmaur/cdnex
